{% set name = "libctl" %}
{% set version = "4.1.1" %}
{% set sha256 = "54eb6c9f4d91b38c3c1ed8c084858596fdd982847404b332cc3d5d5ae002f849" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/stevengj/{{ name }}/releases/download/v{{version}}/{{ name }}-{{version}}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - toolchain
    - gcc
  run:
    - libgcc

test:
  commands:
    - test -f ${PREFIX}/lib/libctlgeom.so     # [linux]
    - test -f ${PREFIX}/lib/libctlgeom.dylib  # [osx]

about:
  home: http:/github.com/stevengj/libctl
  license: GPL-2.0
  license_file: COPYING
  summary:  A Guile-based library for supporting flexible control files in scientific simulations
  doc_url: http://libctl.readthedocs.io
  dev_url: https://github.com/stevengj/libctl

extra:
  recipe-maintainers:
    - ChristopherHogan
