travis:
  secure:
    BINSTAR_TOKEN: ZBfquuvp1B1sNaqIgKe0kbAlUNaKrzsTOgW/UaAFjjolt8jvYsJXLnpElaJBioxaTv9ADBn7XjmyhdmbENFpUHmr1Ow8P0dAmWrB5PA6QL2oLeLDPA6D9Bwte4WRUQkqathIZ6FUO5mQW8P2w1JV3WYUlwRJ0BJvupjaQAcK18qqY55sA9VWXWCJ8dvtTlk3JaMR4fQxS9DSTiSAGLQb5H2QmgglimBfaebEcP8eQAoNYdI+a7bFDj4SBO6XwNYO5SPK4EeJECrlckXTtDDHzMDN3cc3Yc2wT2GGUpyQq30myG2GTSRKlGtoDETXEjsVa9y7xBvsE+MPSzeevaQU8vzIihnC02KBjGEput64ymdSyvHKuIXCo69101CFpP1MZGppSZSUw+yU9uDmWBws96JeBDgrxR8ad8pP2BUE10Jd5C8UaH5Uut35EZrCIY/EZxkjZ2eeZUlKCt7NnemAZDEebXhs0DoDM5X7Zax1KC+ng5s10j3hgzlv6SQ/a5V/COwqqgVbyMDgUE4NmltYgUL6u7czNx6pIzsgtXy6TKRsufltkRNq34IBN0qlhrlmM2D9APHmDzJ8dNbO7i7243+ZeJSrltWSH510J2E3RE+bxYP1vwerYzmP1Yh+z1lgqermyWGngh6Hm7dMMjmlfK+V9fBd5TARZQVchmx7qTs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
